name: Basic Login App
run-name: Basic Login App CI/CD

on:
    push:
        branches:
            - main

jobs:
    testing-taking-build:

        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v6
            
            - name: Setup Flutter
              uses: subosito/flutter-action@v2
              with:
                flutter-version: 3.41.2
                channel: stable
            
            - name: Check Version
              run: flutter --version

            - name: Install Dependencies
              run: flutter pub get
            
            # - name: Analyze App
            #   run: flutter analyze
            
            # - name: Unit Test
            #   run: flutter test test/unit
            
            # - name: Widget Test
            #   run: flutter test test/widget

            # - name: Enable KVM
            #   run: |
            #     echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
            #     sudo udevadm control --reload-rules
            #     sudo udevadm trigger --name-match=kvm

            # - name: Integration Test
            #   uses: reactivecircus/android-emulator-runner@v2
            #   with:
            #     api-level: 29
            #     arch: x86_64
            #     script: | 
            #       flutter devices
            #       flutter test integration_test/ -d emulator-5554
            
            - name: Take Build Debug APK
              run: flutter build apk --debug
            
            - name: Upload Build
              uses: actions/upload-artifact@v7
              with:
                name: debug-build
                path: build/app/outputs/flutter-apk/app-debug.apk

            - name: Push Built APK From Artifact To Firebase
              uses: wzieba/Firebase-Distribution-Github-Action@v1
              with:
                appId: 1:488484105396:android:116a54eb76d4309a1ebbe1
                serviceCredentialsFileContent: ${{ secrets.SERVICE_ACCOUNT }}
                groups: testers
                file: build/app/outputs/flutter-apk/app-debug.apk


            


            
