name: Basic Login App
run-name: Basic Login App CI/CD

on:
    push:
        branches:
            - main

jobs:
    testing-taking-build:

        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v6
            
            - name: Setup Flutter
              uses: subosito/flutter-action@v2
              with:
                flutter-version: 3.41.2
                channel: stable
            
            - name: Check Version
              run: flutter --version

            - name: Install Dependencies
              run: flutter pub get
            
            - name: Analyze App
              run: flutter analyze
            
            - name: Unit Test
              run: flutter test test/unit
            
            - name: Widget Test
              run: flutter test test/widget
            
            - name: Integration Test
              run: flutter test integration_test/
            
            - name: Take Build Debug APK
              run: flutter build apk --debug
            
